language: emacs-lisp
sudo: required
dist: trusty

matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot

env:
  - EMACS_VERSION=24.4
  - EMACS_VERSION=24.5
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1
  - EMACS_VERSION=26.3
  - EMACS_VERSION=snapshot

before_install:
  - export PATH="$HOME/bin:$PATH"
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
  - if [[ $EMACS_VERSION = 24.* ]]; then
        ln -snf Cask-24 Cask;
    else
        ln -snf Cask-25 Cask;
    fi

install:
  - cask install

script:
  - make
